name: CI ubuntu 23.04 no ROS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      
jobs:
  build:
    runs-on: ubuntu-23.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++ git
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++ git

      - name: Setup the project
        run: |
          setup.sh

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
          
      - name: Run Tests
        run: |
          cd bin/tests
          ./unit_tests.exe
